source 'https://github.com/CocoaPods/Specs.git'

target '${POD_NAME}', :exclusive => true do
  pod "${POD_NAME}", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "${POD_NAME}", :path => "../"

  ${INCLUDED_PODS}
end
